<a href="https://colab.research.google.com/github/STARCP/fmml2021/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# practice for numpy

In [ ]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
#given two same dimensional arrays add it element wise
a=np.array([1,2,5])
b=np.array([2,3,5])
print(a+b)

[ 3  5 10]


#given a matrix multipy it with a scalar

In [ ]:
a=np.array([5,3,2,1,5])
print(a*2)

[10  6  4  2 10]


In [ ]:
#create a identity matrix of size 4-by-4
identity_mat=np.identity(4,dtype='int32')
print(identity_mat)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
id_mat=np.zeros((4,4),dtype='int8')
id_mat[[0,1,2,3],[0,1,2,3]]=1
print(id_mat)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
#given a one dimensional array convert it into 2d array
a=np.array([1,2,3,4,5,6,7,8,9])
a.resize((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#convert given 2d float array to 1d int array
a=np.array([x for x in range(9)],dtype='float')
a.resize(3,3)
print(a.astype('int32'))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#convert given 0,1 matrix to boolean type i.e., true of false
a=np.array([i%2 for i in range(9)])
a.resize((3,3))
print(a)
o=a.astype('bool')
print(o)

[[0 1 0]
 [1 0 1]
 [0 1 0]]
[[False  True False]
 [ True False  True]
 [False  True False]]


In [ ]:
#given two arrays implement horizontal stack
a=np.array([i for i in range(1,7)])
b=np.array([i for i in range(7,13)])
a.resize((2,3))
b.resize((2,3))
output=np.hstack((a,b))
print(output)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
#given two arrays implement vertical stack
a=np.array([x for x in range(1,7)])
b=np.array([x for x in range(7,13)])
print('b=',b)
print('a=',a)
output=np.vstack((a,b))
print(output)

b= [ 7  8  9 10 11 12]
a= [1 2 3 4 5 6]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
#create a array of custom number i.e., 2,4,6,...,100
a=np.arange(2,101,2)
print(a)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [43]:
#print all the elements which are common in both arrays
a=np.array([1,3,4,5,8,9])
b=np.array([2,3,6,5,8,1])
output=np.where(a==b)
print(a[output])

[3 5 8]
